ClothBazar.Web/ViewModels/ProductViewModels.cs
using ClothBazar.Entities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Threading;
using System.Web;

namespace ClothBazar.Web.ViewModels
{
    public class ProductSearchViewModel
    {
        public int pageNo { get; set; }
        public List<Product> Products { get; set; }

        public string SearchTerm { get; set; }
    }
    public class NewProductViewModel
    {
        //public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public decimal Price { get; set; }
        public int CategoryId{ get; set; }
        public string ImageURL { get; set; }
        public List<Category> AvaliableCategories { get; set; }
    }
    public class EditProductViewModels
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public decimal Price { get; set; }
        public int CategoryId { get; set; }
        public string ImageURL { get; set; }
        public List<Category> AvaliableCategories { get; set; }

    }
    public class ProductViewModels
    {
        public Product Product { get; set; }
    }
}

ClothBazar.Web/Controllers/ProductController.cs
using ClothBazar.Entities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ClothBazar.Services;
using ClothBazar.Web.ViewModels;

namespace ClothBazar.Web.Controllers
{
    [Authorize(Roles = "Admin")]
    public class ProductController : Controller
    {
       //ProductSearchViewModel model = new ProductSearchViewModel();
        // ProductsService productsService = new ProductsService();
       // CategoriesServices categoryservice = new CategoriesServices();
        // GET: Product
        public ActionResult Index()
        {
            return View();
        }
        
        public ActionResult ProductTable(string Search,int? pageNo)
        {
            ProductSearchViewModel model = new ProductSearchViewModel();

            model.pageNo = pageNo.HasValue? pageNo.Value>0 ? pageNo.Value:1:1;
            //similar to above
            //if(pageNo.HasValue)
            //{
            //    if(pageNo.Value>0)
            //    {
            //        model.pageNo = pageNo.Value;
            //    }
            //    else
            //    {
            //        model.pageNo = 1;
            //    }
            //}
            //else
            //{
            //    model.pageNo = 1;
            //}
            model.Products = ProductsService.Instance.GetProducts(model.pageNo);
            if (string.IsNullOrEmpty(Search) == false)
            {
                model.SearchTerm = Search;
                model.Products = model.Products.Where(p => p.Name != null && p.Name.ToLower().Contains(Search.ToLower())).ToList();
            }
            /*foreach(var p in product)
            {
                if(p.Name==Search)
                {

                }
            }*/
            return PartialView(model);
        }
        [HttpGet]
        public ActionResult Create()
        {
            //CategoriesServices cateroryservices = new CategoriesServices();
            NewProductViewModel model = new NewProductViewModel();

            model.AvaliableCategories = CategoriesServices.Instance.GetallCategories();
            return PartialView(model);
        }
        [HttpPost]
        public ActionResult Create(NewProductViewModel model)
        {
           // CategoriesServices categoryservice = new CategoriesServices();
            var newproduct = new Product();
            newproduct.Name = model.Name;
            newproduct.Description = model.Description;
            newproduct.Price = model.Price;
            newproduct.Category =CategoriesServices.Instance.GetCategorie(model.CategoryId);
            newproduct.ImageURL = model.ImageURL;
            ProductsService.Instance.SaveProduct(newproduct);
            return RedirectToAction("ProductTable");
        }
        [HttpGet]
        public ActionResult Edit(int Id)
        {
            EditProductViewModels model = new EditProductViewModels();
            var product =ProductsService.Instance.GetProduct(Id);

            model.Id = product.Id;
            model.Name = product.Name;
            model.Description = product.Description;
            model.Price = product.Price;
            model.CategoryId = product.Category!=null?product.Category.Id:0;
            model.ImageURL = product.ImageURL;

            model.AvaliableCategories = CategoriesServices.Instance.GetallCategories();
            return PartialView(model);
        }
        [HttpPost]
        public ActionResult Edit(EditProductViewModels model)
        {
            var exitingproduct = ProductsService.Instance.GetProduct(model.Id);
            exitingproduct.Name = model.Name;
            exitingproduct.Description = model.Description;
            exitingproduct.Price = model.Price;
            exitingproduct.Category = CategoriesServices.Instance.GetCategorie(model.CategoryId);
            exitingproduct.ImageURL = model.ImageURL;
            
            ProductsService.Instance.UpdateProduct(exitingproduct);
            return RedirectToAction("ProductTable");
        }
        [HttpPost]
        public ActionResult Delete(int Id)
        {
            ProductsService.Instance.DeleteProduct(Id);
            return RedirectToAction("ProductTable");
        }
        public ActionResult Detail(int Id)
        {
            ProductViewModels model = new ProductViewModels();
            model.Product = ProductsService.Instance.GetProduct(Id);
            return View(model);
        }
    }
}

ClothBazar.Web/Controllers/WidgetsController.cs
using ClothBazar.Services;
using ClothBazar.Web.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ClothBazar.Web.Controllers
{
    public class WidgetsController : Controller
    {
        // GET: Widgets
        public ActionResult Products(bool IsLatestProducts,int? CategoryId/*,bool? IsCategoryProducts*/)
        {
            ProductsWidgetViewModel model = new ProductsWidgetViewModel();
            model.IsLatestProducts = IsLatestProducts;
            if (IsLatestProducts)
            {
                model.Products = ProductsService.Instance.GetLatestProducts(4);
            }
            else if(CategoryId.HasValue&&CategoryId>0)
            {
                model.Products = ProductsService.Instance.GetProductsByCategory(CategoryId.Value,4);
            }
            else
            {
                model.Products = ProductsService.Instance.GetProducts(1, 8);
            }
            return PartialView(model);
        }
    }
}

ClothBazar.Web/Views/Product/Create.cshtml
@model ClothBazar.Web.ViewModels.NewProductViewModel
@{
    ViewBag.Title = "Create";
    var imageURL = "/Content/images/system/default image.png";
}
<h2>Create Product</h2>

<form id="createproduct">
    <div class="row">
        <div class="col-md-8">
            <div class="form-group">
                <label>Category</label>
                <select class="form-control" name="CategoryID">
                    @foreach (var category in Model.AvaliableCategories)
                    {

                        <option value="@category.Id">@category.Name</option>
                    }
                </select>

            </div>
            <div class="form-group">
                <label class="form-control">Product Name</label>
                <input class="form-control" name="name" />
            </div>
            <div class="form-group">
                <label class="form-control">Description</label>
                <input class="form-control" name="Description" />
            </div>
            <div class="form-group">
                <label class="form-control">Price</label>
                <input class="form-control" name="Price" />
            </div>
            <div class="form-group">
                <label class="form-control">Image</label>
                <input id="ImageURL" name="ImageURL" type="hidden" />
                <input class="form-control" id="ImageUpload" name="Image" type="file" accept=".jpg, .png" />
            </div>
            <button id="saveBtn" class="btn btn-danger" type="button">save</button>
            <button id="cancelBtn" class="btn btn-danger" type="reset">Cancel</button>
        </div>
        <div class="col-md-4">
            <div class="thumb">
                <img id="productImage" class="img-thumbnail img-fluid" src="@imageURL" />
            </div>
        </div>
    </div>
    @*<div class="form-group">
        <label>Category</label>
        <select class="form-control" name="CategoryID">
            @foreach (var category in Model.AvaliableCategories)
            {

                <option value="@category.Id">@category.Name</option>
            }
        </select>

    </div>
    <div class="form-group">
        <label class="form-control">Product Name</label>
        <input class="form-control" name="name" />
    </div>
    <div class="form-group">
        <label class="form-control">Description</label>
        <input class="form-control" name="Description" />
    </div>
    <div class="form-group">
        <label class="form-control">Price</label>
        <input class="form-control" name="Price" />
    </div>
    <button id="saveBtn" class="btn btn-danger" type="button">save</button>
    <button id="cancelBtn" class="btn btn-danger" type="reset">Cancel</button>*@
</form>



<script>
    $("#ImageUpload").change(function () {

        var element = this;
        var formData = new FormData();
        var totalfiles = element.files.length;

        for (var i = 0; i < totalfiles; i++) {
            var file = element.files[i];
            formData.append("Photo", file);
        }
        $.ajax({
            type: 'post',
            url:'@Url.Action("UpdateImage", "shared")',// '/shared/UpdateImage',
            datatype: 'JSON',
            data: formData,
            contentType: false,
            processData: false

        })
            .done(function (response) {
                debugger;
                console.log(response)
                if (response.Success) {
                    $("#ImageURL").val(response.ImageURL);
                    $("#productImage").attr("src", response.ImageURL);
                }
            })
            .fail(function (XMLHttpRequest, textStatus, errorThrown) {
                alert("fail");
            });
    });

    $("#saveBtn").click(function () {
        var searchvalue = $("#searchTxt").val();

        $.ajax({
            type:'post',
            url: '@Url.Action("Create","Product")',//'/Product/create',
            data:$('#createproduct').serialize()
        })
            .done(function (response) {
                $("#tablecontainer").html(response);
                $("#actioncontainer").html("");
                focusAction("actioncontainer");
            })
            .fail(function (XMLHttpRequest, textStatus, errorThrown) {
                alert("fail");
                //swal({
                //    title: "Warning",
                //    text: "Pleace enter all required fields",
                //    icon: "warning",
                //    buttons: true,
                //    dangerMode:true,
                //})
            });
    });
    $("#cancelBtn").click(function () {
        $("#actioncontainer").html("");
        focusAction("actioncontainer");
    });
</script>

ClothBazar.Web/Views/Product/Detail.cshtml
@model ClothBazar.Web.ViewModels.ProductViewModels
@{
    ViewBag.Title = "Detail";
}
@if (Model != null && Model.Product != null)
{
    var defaultimageURL = "/Content/images/system/default image.png";

    var imageURL = string.IsNullOrEmpty(Model.Product.ImageURL) ? defaultimageURL : Model.Product.ImageURL;

<h2>Detail</h2>
<div class="page-title parallax parallax1">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="page-title-heading">
                    <h1 class="title">
                        @Model.Product.Name
                    </h1>

                </div>
            </div>
        </div>
    </div>
</div>
<section class="flat-row main-shop-details">
    <div class="container">
        <div class="row">
            <div class="col-md-6">
                <div class="wrap-flexslider">
                    <div class="inner">
                        <div class="flexslider style-1 has-relative">
                            <ul class="slides">
                                <li data-thumb="@imageURL">
                                    <img src="@imageURL" alt="Image" />
                                    <div class="flat-icon style-1">
                                        <a href="@imageURL"class="zoom-popup"><span class="fa fa-search-plus"></span></a>
                                    </div>
                                </li>
                            </ul>
                        </div>
                    </div>

                </div>
            </div>
        </div>
    </div>
    <div class="col-md-6">
        <div class="inner">
            <div class="product title">@Model.Product.Name</div>
            <div>

            </div>
            <p>@Model.Product.Description</p>
            <div class="price">
                <ins><span class="amount">
                    $@Model.Product.Price
                    </span></ins>
            </div>
            <div class="product-categories">
                <span>categories:</span><a href="#">@Model.Product.Category.Name</a>
            </div>
        </div>
    </div>
</section>
<section class="flat-row shop-details-content">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="flat-tabs style-1 has border">
                    <div class="inner">
                        <ul class="menu-tab">
                            <li class="active">Reviews</li>
                        </ul>
                    </div>
                </div>
            </div>

        </div>

    </div>

</section>
<section class="flat-row shop-related">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="title-section margine-button-52">
                    <h2 class="title">
                        Related Products
                    </h2>
                </div>
                @{Html.RenderAction("products", "Widgets", new { IsLatestProducts = false, CategoryId = Model.Product.Category.Id });
                }
            </div>
        </div>
    </div>

</section>
}

ClothBazar.Web/Views/Product/Edit.cshtml
@model ClothBazar.Web.ViewModels.EditProductViewModels
@{
    ViewBag.Title = "Edit";

    var imageURL = !string.IsNullOrEmpty(Model.ImageURL)?Model.ImageURL: "/Content/images/system/default image.png";
}

<h2>Edit product</h2>

@*<form id="editproduct">
    <input type="hidden" name="Id" value="@Model.Id" />
    <label>Product Name</label>
    <input name="name" value="@Model.Name" />
    <br />
    <label>Description</label>
    <input name="Description" value="@Model.Description" />
    <br />
    <label>Price</label>
    <input name="Price" value="@Model.Price" />
    <br />
    <button id="updateBtn" type="button">update</button>
</form>*@

<form id="editproduct">
    <input type="hidden" name="Id" value="@Model.Id" />
    <div class="row">
        <div class="form-group">
            @*<input type="hidden" name="Id" value="@Model.Id" />*@
            <label>Category</label>
            <select class="form-control" name="CategoryID">
                @foreach (var category in Model.AvaliableCategories)
                {
                    var selected = category.Id == Model.CategoryId ? "selected" : string.Empty;
                    <option value="@category.Id" @selected>@category.Name</option>
                }
            </select>

        </div>
        <div class="form-group">
            <label class="form-control">Product Name</label>
            <input name="name" class="form-control" value="@Model.Name" />
        </div>
        <div class="form-check">
            <label class="form-control">Description</label>
            <input name="Description" class="form-control" value="@Model.Description" />
        </div>
        <div class="form-check">
            <label class="form-control">Price</label>
            <input name="Price" class="form-control" value="@Model.Price" />
        </div>
        <div class="form-group">
            <label class="form-control">Image</label>
            <input id="ImageURL" name="ImageURL" type="hidden" />
            <input class="form-control" id="ImageUpload" name="Image" type="file" accept=".jpg, .png" />
        </div>
        <button id="updateBtn" class="btn btn-danger" type="button">Update</button>
        <button id="cancelBtn" class="btn btn-danger" type="reset">cancel</button>
    </div>-->
    <div class="col-md-4">
        <div class="thumb">
            <img id="productImage" class="img-thumbnail img-fluid" src="@imageURL" />
        </div>
    </div>-->


    @*<div class="form-group">
            <input type="hidden" name="Id" value="@Model.Id" />
            <label>Category</label>
            <select class="form-control" name="CategoryID">
                @foreach (var category in Model.AvaliableCategories)
                {
                    var selected = category.Id == Model.CategoryId ? "selected" : string.Empty;
                    <option value="@category.Id" @selected>@category.Name</option>
                }
            </select>

        </div>
        <div class="form-group">
            <label class="form-control">Product Name</label>
            <input name="name" class="form-control" value="@Model.Name" />
        </div>
        <div class="form-check">
            <label class="form-control">Description</label>
            <input name="Description" class="form-control" value="@Model.Description" />
        </div>
        <div class="form-check">
            <label class="form-control">Price</label>
            <input name="Price" class="form-control" value="@Model.Price" />
        </div>
        <button id="updateBtn" class="btn btn-danger" type="button">Update</button>
        <button id="cancelBtn" class="btn btn-danger" type="reset">cancel</button>*@
</form>


<script>

     $("#ImageUpload").change(function () {

        var element = this;
        var formData = new FormData();
        var totalfiles = element.files.length;

        for (var i = 0; i < totalfiles; i++) {
            var file = element.files[i];
            formData.append("Photo", file);
        }
        $.ajax({
            type: 'post',
            url:'@Url.Action("UpdateImage", "shared")',// '/shared/UpdateImage',
            datatype: 'JSON',
            data: formData,
            contentType: false,
            processData: false

        })
            .done(function (response) {
                debugger;
                console.log(response)
                if (response.Success) {
                    $("#ImageURL").val(response.ImageURL);
                    $("#productImage").attr("src", response.ImageURL);
                }
            })
            .fail(function (XMLHttpRequest, textStatus, errorThrown) {
                alert("fail");
            });
    });

    $("#updateBtn").click(function () {

        $.ajax({
            type: 'post',
            url: '@Url.Action("edit", "Product")',//'/Product/Edit',
            data: $('#editproduct').serialize()
        })
            .done(function (response) {
                $("#tablecontainer").html(response);
                $("#actioncontainer").html("");
                focusAction("tablecontainer");
            })
            .fail(function (XMLHttpRequest, textStatus, errorThrown) {
                alert("fail");
            });
    });

    $("#cancelBtn").click(function () {
        $("#actioncontainer").html("");
        focusAction("tablecontainer");
    });
</script>

ClothBazar.Web/Views/Product/Index.cshtml
@{
    ViewBag.Title = "Products";
}

<section class="flat-row flat-iconbox">
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <div class="title-section">
                <h2 class="title">
                    Product Table
                </h2>
            </div>
        </div>
    </div>
    <h2 align="centre">Index</h2>
    <div align="center" id="tablecontainer">
        @{
            Html.RenderAction("ProductTable");

            // Html.RenderAction("create");
        }
    </div>
    <div align="center" id="actioncontainer">

    </div>
</div>
</section>


<script>
    function focusAction(controlToFocus) {
        $('html, body').animate({
            scrollTop: $("#" + controlToFocus).offset().Top
        }, 1000);
    }
</script>

ClothBazar.Web/Views/Product/ProductTable.cshtml
@model ClothBazar.Web.ViewModels.ProductSearchViewModel
    @{
    ViewBag.Title = "ProductTable";
}
<div>
    <form method="post">
        <div class="row">
            <div class="col-md-8">
                <div class="form-group">
                    <label>search</label>
                    <input class="form-control" id="searchTxt" name="Search" value="@Model.SearchTerm"/>
                </div>
            </div>
            <div class="col-md-4">
                <div class="form-group">
                    <label>actions</label>
                    <div class="row">
                        <div class="col-md-4 pr-0">
                            <button style="color:white;background-color:yellowgreen;" class="btn-btn-danger form-control" type="button" id="SearchBtn">Search</button>
                        </div>
                        <div class="col-md-4 pr-0">
                            <button style="color:white;background-color:yellowgreen;" class="btn-btn-danger form-control" type="reset" id="resetBtn">Reset</button>
                        </div>
                        <div class="col-md-4 pr-0">
                            <button style="color:white;background-color:yellowgreen;" class="btn-btn-danger form-control" type="button" id="newBtn">New</button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </form>
</div>

<div>
    <table class="table table-striped">
        <thead>
            <tr>
                <th class="font-weight-bold">product Name</th>
                <th class="font-weight-bold">category</th>
                <th class="font-weight-bold">Price</th>
                <th class="font-weight-bold wrap-td">Actions</th>
            </tr>
        </thead>
        <tbody>
            @if (Model.Products != null && Model.Products.Count > 0)
            {
            foreach (var product in Model.Products)
            {
                <tr>

                    <td>@product.Name</td>
                    <td>
                        @if (product.Category != null)
                        {
                            <text>@product.Category.Name</text>
                        }
                        else
                        {
                            <text>-</text>
                        }

                    </td>
                    <td>@product.Price</td>
                    <td class="wrap-td">
                        <button class="editBtn" data-id="@product.Id">Edit</button>
                        <button class="deleteBtn" data-id="@product.Id">delete</button>
                        <button class="addtoCart" data-id="@product.Id">ADD TO CART</button>
                    </td>
                </tr>
                }
            }
            else
            {
                <tr>
                    <td colspan="4">no products found

                    </td>
                </tr>
            }
        </tbody>
    </table>
    <div>
        @if(Model.pageNo!=1)
        {
        <button class="pageButtons" data-pageNo="@(Model.pageNo-1)">Previous</button>
        }
        <button class="pageButtons" data-pageNo="@(Model.pageNo+1)">Next</button>
    </div>
</div>


<script>
   // $('#ProductTable').DataTable();
    $(".pageButtons").click(function () {
        $.ajax({
            url: '@Url.Action("ProductTable", "Product")',/*'/Product/productTable',*/
            data: {
                pageNo: $(this).attr("data-pageNo")
            }
        })
            .done(function (response) {
                $("#tablecontainer").html(response);
                focusAction();
            })

            .fail(function (XMLHttpRequest, textStatus, errorThrown) {
                alert("fail");
            });
    });

    //$("#NextRecords").click(function () {
    //    $.ajax({
    //        url: '/Product/productTable',
    //        data: {
    //            pageNo: $(this).attr("data-pageNo")
    //        }
    //    })
    //        .done(function (response) {
    //            $("#tablecontainer").html(response);
    //            focusAction();
    //        })

    //        .fail(function (XMLHttpRequest, textStatus, errorThrown) {
    //            alert("fail");
    //        });
    //});

    $("#SearchBtn").click(function () {
        var searchvalue = $("#searchTxt").val();

        $.ajax({
            url: '@Url.Action("ProductTable", "Product")',//'/Product/ProductTable',
            data: {
                search: searchvalue
            }
        })
            .done(function (response) {
                $("#tablecontainer").html(response);
            })
            .fail(function (XMLHttpRequest, textStatus, errorThrown) {
                alert("fail");
            });
    });

    $("#resetBtn").click(function () {
        var searchvalue ='';

        $.ajax({
            url: '@Url.Action("ProductTable", "Product")',//'/Product/ProductTable',
            data: {
                search: searchvalue
            }
        })
            .done(function (response) {
                $("#tablecontainer").html(response);
            })
            .fail(function (XMLHttpRequest, textStatus, errorThrown) {
                alert("fail");
            });
    });

    $("#newBtn").click(function () {
        $.ajax({
            url: '@Url.Action("Create", "Product")',//'/Product/Create',
        })
            .done(function (response) {
                $("#actioncontainer").html(response);
                focusAction("actioncontainer");
            })

            .fail(function (XMLHttpRequest, textStatus, errorThrown) {
                alert("fail");
            });
    });
    $(".editBtn").click(function () {
        $.ajax({

            url: '@Url.Action("edit", "Product")',//'/Product/edit',
            data: {
                Id: $(this).attr('data-id')
            }
        })
            .done(function (response) {
                $("#actioncontainer").html(response);
                focusAction("actioncontainer");
            })

            .fail(function (XMLHttpRequest, textStatus, errorThrown) {
                alert("fail");
            });
    });
    $(".deleteBtn").click(function () {
        swal({
            title: "Confirm?",
            text: "Are you sure you want delete product?",
            icon: "warning",
            buttons: true,
            dangerMode: true,
        })
            .then((willDelete) => {
                if (willDelete) {
                    $.ajax({
                type: 'post',
                url: '@Url.Action("delete", "Product")',//'/Product/delete',
                data: {
                    Id: $(this).attr('data-id')
                }
            })
                .done(function (response) {
                    $("#tablecontainer").html(response);
                    swal("Recorded deleted successfully.", {
                        icon: "success",
                    });

                })
                .fail(function (XMLHttpRequest, textStatus, errorThrown) {
                    alert("fail");

                });

                //} else {
                //    swal("Your imaginary file is safe!");
                }
            });

        //var confirmDelete = confirm("Are you sure you want delete product?");
        //if (confirmDelete) {
        //    $.ajax({
        //        type: 'post',
        //        url: '/Product/delete',
        //        data: {
        //            Id: $(this).attr('data-id')
        //        }
        //    })
        //        .done(function (response) {
        //            $("#tablecontainer").html(response);
        //        })
        //        .fail(function (XMLHttpRequest, textStatus, errorThrown) {
        //            alert("fail");
        //        });
        //}
    });
    var products = [];
    $(".addtoCart").click(function () {
        var productID = $(this).attr('data-id');
        products.push(productID);

        $.cookie('CartProducts',
            products.join('-'),
            { path: '/' }
        );

        alert("product added to cart.");
    });
    function focusAction() {
            $('html, body').animate({
                scrollTop: $("actioncontainer").offset().Top - 100
            }, 1000);
        }
</script>